//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherInfo
    {
        public int WeatherInfoID { get; set; }
        public int LocationID { get; set; }
        public string Time { get; set; }
        public string Description { get; set; }
        public string Temp { get; set; }
        public string Icon { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
